spring:
  application:
    name: spring-boot-resilience4j

resilience4j:
  circuitbreaker:
    instances:
      backendA:
        # ?????????
        register-health-indicator: true
        # ?????????????
        sliding-window-size: 5
        # ???????????
        permitted-number-of-calls-in-half-open-state: 3
        # ????????????
        wait-duration-in-open-state: 10s
        # ????????????????
        failure-rate-threshold: 50
  ratelimiter:
    instances:
      backendB:
        # ???????????????
        limit-for-period: 10
        # ?????????
        limit-refresh-period: 1s
        # ?????????
        timeout-duration: 500ms
  retry:
    instances:
      backendC:
        # ??????
        max-attempts: 3
        # ?????????
        wait-duration: 500ms
  timelimiter:
    instances:
      backendD:
        # ?????????
        timeout-duration: 1s
  bulkhead:
    instances:
      backendE:
        # ???????
        max-concurrent-calls: 10
        # ???????????
        max-wait-duration: 500ms