server:
  port: 8081
spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    # connection pool
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
